### ISSUE TITLE
Could you add a screen shot?

### ISSUE THREAD

**Issue by unixorn** [kitian616/tq-zsh-theme#1]
I'd like to add this to the [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) list, but I prefer to add themes that have screenshots so the users can see what they're getting before installing.

Thanks!

**Comment by kitian616** [comment]
Ok, I will do it soon, many thanks

在 2017年6月7日，22:17，Joe Block <notifications@github.com<mailto:notifications@github.com>> 写道：


I'd like to add this to the awesome-zsh-plugins<https://github.com/unixorn/awesome-zsh-plugins> list, but I prefer to add themes that have screenshots so the users can see what they're getting before installing.

Thanks!
